### ISSUE TITLE
Cannot compile with make

### ISSUE THREAD

**Issue by someone2026** [the-lambda-way/bruteforce-enigma#11]
```
process_begin: CreateProcess(NULL, g++ -std=c++20 -pthread -Iinclude/ -Iexternal/ -MM include/bruteforce-enigma.h, ...) failed.
process_begin: CreateProcess(NULL, g++ -std=c++20 -pthread -Iinclude/ -Iexternal/ -MM include/bruteforce-enigma.h, ...) failed.
File not found - TESTS/
File not found - -NAME
process_begin: CreateProcess(NULL, g++ -std=c++20 -pthread -Iinclude/ -Iexternal/ -MM include/bruteforce-enigma.h, ...) failed.
process_begin: CreateProcess(NULL, g++ -std=c++20 -pthread -Iinclude/ -Iexternal/ -MM include/bruteforce-enigma.h, ...) failed.
process_begin: CreateProcess(NULL, g++ -std=c++20 -pthread -Iinclude/ -Iexternal/ -MM include/bruteforce-enigma.h, ...) failed.
process_begin: CreateProcess(NULL, g++ -std=c++20 -pthread -Iinclude/ -Iexternal/ -MM include/bruteforce-enigma.h, ...) failed.
'printf' is not recognized as an internal or external command,
operable program or batch file.
make: *** [crack_enigma] Error 1
```

**Comment by the-lambda-way** [comment]
Sorry for taking so long to get back to you. It looks like you might be trying to run the makefile on Windows? If that's the case, you might need to run the makefile from a Windows Subsystem for Linux environment, like the bash shell that comes with it. Since WSL is now a robust feature of Windows and easy to use, I have not bothered to make compiling this program Windows-friendly.

I haven't kept up to speed with the status of WSL, so I don't know if it comes preinstalled nowadays. I found these two pages for you if it needs to be installed first.

https://learn.microsoft.com/en-us/windows/wsl/install
https://learn.microsoft.com/en-us/windows/wsl/about

I'm willing to help in any way you need if you have other questions or problems.
